version: "3"
services:
  db:
    image: postgres:12
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  db_test:
    image: postgres:12
    volumes:
      - ./db_test:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: auth_service_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  go:
    build: ./docker/go
    command:
      - "/bin/bash"
      - "-c"
      - "GO_ENV=develop go run main.go"
    volumes:
      - ./go:/usr/src/go_auth
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db_test
