name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PJ_ACTOR: imanau
  PJ_REPO: go_auth

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v1
        with:
          repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
          ref: refs/heads/master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker set up
        run: |
          make up_for_cli
      - name: Execute tests 
        run: |
          make test
     
